### ISSUE TITLE
Невозможность перевода всей суммы со счета в методе transfer класса Bank.

### ISSUE THREAD

**Issue by Aisenkora** [Aisenkora/javaqa_team_diplom#13]
# Описание

Метод transfer класса Bank не выполняет перевод средств, если переводить всю сумму со счета.

# Локация дефекта

https://github.com/Aisenkora/javaqa_team_diplom/blob/733d6326c3ab2bb42ade9c9f210ba9cf7f69bb7d/src/main/java/ru/netology/javaqadiplom/Bank.java#L16-L24

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Aisenkora/javaqa_team_diplom/blob/main/src/main/java/ru/netology/javaqadiplom/Bank.java) в IDEA
2. Cоздать объект класса Bank с балансом счета с которого переводим: 2000, балансом счета на который переводим: : 1000.
3. Совершить перевод на сумму 2000 рублей.

*Ожидаемый результат - Сумма на счете с которого переводим: 0 рублей.
*Фактический результат - Сумма на счете на который переводим: 2000 рублей.

https://github.com/Aisenkora/javaqa_team_diplom/blob/733d6326c3ab2bb42ade9c9f210ba9cf7f69bb7d/src/test/java/ru/netology/javaqadiplom/BankTest.java#L79-L95

# Скриншот

![вся сумма со счета](https://github.com/Aisenkora/javaqa_team_diplom/assets/164934661/65c5370f-2a0f-4717-bef7-318fca85842a)

# Окружение

Операционная система: Windows 10
IDE: IntelliJ IDEA Community Edition 2024.1.2
Java: OpenJDK 11

@KseniiaVv

**Comment by KseniiaVv** [comment]
fix #13
