### ISSUE TITLE
В методе yearChange класса CreditAccount нарушена логика расчета процентной ставки.

### ISSUE THREAD

**Issue by Aisenkora** [Aisenkora/javaqa_team_diplom#16]
# Описание

В методе yearChange класса CreditAccount нарушена логика расчета процентной ставки. Сперва необходимо умножить баланс на процентную ставку, и только потом разделить результат на 100.

# Локация дефекта

https://github.com/Aisenkora/javaqa_team_diplom/blob/06ffdecb962bb016d2eecd70a86f9fdb3941716c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L105-L112

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Aisenkora/javaqa_team_diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Cоздать объект класса СreditAccount с начальным балансом: 1000, кредитным лимитом: 500, кредитной ставкой: 80.
3. Совершить покупку на сумму 1099 рублей.

*Ожидаемый результат - Процентная ставка: -79.
*Фактический результат - Процентная ставка: 0.

https://github.com/Aisenkora/javaqa_team_diplom/blob/e2379134453656d3923abd3c5f6343e6f2f77d33/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L181-L190

# Скриншот

![проц](https://github.com/Aisenkora/javaqa_team_diplom/assets/164934661/8a08836b-f730-4e61-a610-c99c6e78093f)

# Окружение

Операционная система: Windows 10
IDE: IntelliJ IDEA Community Edition 2024.1.2
Java: OpenJDK 11

@KseniiaVv

**Comment by KseniiaVv** [comment]
fix #16
