### ISSUE TITLE
В конструкторе класса CreditAccount переменная initialBalance не проверяется на отрицательное значение 

### ISSUE THREAD

**Issue by Aisenkora** [Aisenkora/javaqa_team_diplom#2]
# Описание

В конструкторе класса CreditAccount должна проверяться на отрицательное значение переменная initialBalance.

# Локация дефекта

https://github.com/Aisenkora/javaqa_team_diplom/blob/673970e49e859e2fc696dd7f450f4ebac91346e4/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Aisenkora/javaqa_team_diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Cоздать объект класса СreditAccount с начальным балансом: -1000, кредитным лимитом: 500, кредитной ставкой: 15.

*Ожидаемый результат - выброс исключения IllegalArgumentException.
*Фактический результат - исключение IllegalArgumentException отсутствует.

https://github.com/Aisenkora/javaqa_team_diplom/blob/3bf11d3d803f905b7b886f69d450c0cad57dbc94/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L159

# Скриншот

![выброс исключения отсутствует](https://github.com/Aisenkora/javaqa_team_diplom/assets/164934661/afdf682d-4aea-4aeb-8cc3-13fa2fa94c9a)

# Окружение

Операционная система: Windows 10
IDE: IntelliJ IDEA Community Edition 2024.1.2
Java: OpenJDK 11

@KseniiaVv

**Comment by KseniiaVv** [comment]
fix #1, #2, #3, #4, #5
