### ISSUE TITLE
Метод Transfer класса Bank не возвращает списанные средства на счет from, при неудачном зачислении на счет to

### ISSUE THREAD

**Issue by Aisenkora** [Aisenkora/javaqa_team_diplom#21]
# Описание

Метод Transfer класса Bank не возвращает списанные средства на счет from, при неудачном зачислении на счет to. При неудачной операции зачисления, метод должен возвращать деньги обратно.

# Локация дефекта

https://github.com/Aisenkora/javaqa_team_diplom/blob/8509d250c1519df846e8f1f5d0dc4d9ed895fd6f/src/main/java/ru/netology/javaqadiplom/Bank.java#L17-L30

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Aisenkora/javaqa_team_diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/Bank.java) в IDEA
2. Cоздать объект from класса CreditAccount с начальным балансом: 9001, кредитным лимитом: 500, кредитной ставкой: 10.
3. Cоздать объект to класса SavingAccount с начальным балансом: 1000, минимальным балансом: 100, максимальным балансом: 10000, процентной ставкой: 5.
4. Выполнить перевод со счета "From" на счет "To"  на сумму 9001 рублей.

*Ожидаемый результат - Сумма на счете from: 9001.
*Фактический результат - Сумма на счете from: 0.

https://github.com/Aisenkora/javaqa_team_diplom/blob/8509d250c1519df846e8f1f5d0dc4d9ed895fd6f/src/test/java/ru/netology/javaqadiplom/BankTest.java#L290-L303

# Скриншот

![gjcktlybq 11](https://github.com/Aisenkora/javaqa_team_diplom/assets/164934661/c0a336af-6372-4af2-b14c-d24a98041539)

# Окружение

Операционная система: Windows 10
IDE: IntelliJ IDEA Community Edition 2024.1.2
Java: OpenJDK 11

@KseniiaVv

**Comment by KseniiaVv** [comment]
Fix #21
