### ISSUE TITLE
В методе pay класса CreditAccount отсутствует логика проверки условий

### ISSUE THREAD

**Issue by Aisenkora** [Aisenkora/javaqa_team_diplom#3]
# Описание

В методе pay класса CreditAccount отсутствует логика проверки условий. Сперва должно проверяться условие, затем вычитаться сумма из баланса.

# Локация дефекта

https://github.com/Aisenkora/javaqa_team_diplom/blob/3bf11d3d803f905b7b886f69d450c0cad57dbc94/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40-L51

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Aisenkora/javaqa_team_diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Cоздать объект класса СreditAccount с начальным балансом: 1000, кредитным лимитом: 500, кредитной ставкой: 15.
3. Совершить покупку на сумму 500 рублей.

*Ожидаемый результат - Сумма на счете: 500 рублей.
*Фактический результат - Сумма на счете: -500 рублей.

https://github.com/Aisenkora/javaqa_team_diplom/blob/3bf11d3d803f905b7b886f69d450c0cad57dbc94/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L55-L65

# Скриншот

![пэй](https://github.com/Aisenkora/javaqa_team_diplom/assets/164934661/dac8a060-f4b5-43c4-b7e3-5b65c9374e03)

# Окружение

Операционная система: Windows 10
IDE: IntelliJ IDEA Community Edition 2024.1.2
Java: OpenJDK 11

@KseniiaVv

**Comment by KseniiaVv** [comment]
fix #1, #2, #3, #4, #5
