### ISSUE TITLE
В методе add класса CreditAccount баланс не увеличивается на сумму пополнения.

### ISSUE THREAD

**Issue by Aisenkora** [Aisenkora/javaqa_team_diplom#4]
# Описание

В методе add класса CreditAccount отсутствует вычисление суммы баланса и пополнения. В результате успешного вызова этого метода, баланс должен увеличиться на сумму пополнения.

# Локация дефекта

https://github.com/Aisenkora/javaqa_team_diplom/blob/3bf11d3d803f905b7b886f69d450c0cad57dbc94/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65-L71

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Aisenkora/javaqa_team_diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Cоздать объект класса СreditAccount с начальным балансом: 1000, кредитным лимитом: 500, кредитной ставкой: 15.
3. Пополнить счет на сумму 500 рублей.

*Ожидаемый результат - Сумма на счете: 1500 рублей.
*Фактический результат - Сумма на счете: 500 рублей.

https://github.com/Aisenkora/javaqa_team_diplom/blob/3bf11d3d803f905b7b886f69d450c0cad57dbc94/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L19-L29

# Скриншот

![адд](https://github.com/Aisenkora/javaqa_team_diplom/assets/164934661/fffef368-b2c5-4fae-bfc8-f5d26c90ab9e)

# Окружение

Операционная система: Windows 10
IDE: IntelliJ IDEA Community Edition 2024.1.2
Java: OpenJDK 11

@KseniiaVv

**Comment by KseniiaVv** [comment]
fix #1, #2, #3, #4, #5
