### ISSUE TITLE
Начисление процентов при положительном балансе в методе yearChange класса CreditAccount

### ISSUE THREAD

**Issue by Aisenkora** [Aisenkora/javaqa_team_diplom#5]
# Описание

Метод yearChange класса CreditAccount не учитывает, что проценты должны начисляться только в том случае, если баланс отрицательный.

# Локация дефекта

https://github.com/Aisenkora/javaqa_team_diplom/blob/3bf11d3d803f905b7b886f69d450c0cad57dbc94/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L81-L84

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Aisenkora/javaqa_team_diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Cоздать объект класса СreditAccount с начальным балансом: 300, кредитным лимитом: 500, кредитной ставкой: 15.
3. Произвести операцию расчета процентов.

*Ожидаемый результат - Процент: 0.
*Фактический результат - Процент: 45.

https://github.com/Aisenkora/javaqa_team_diplom/blob/3bf11d3d803f905b7b886f69d450c0cad57dbc94/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L115-L123

# Скриншот

![проценты при +балансе](https://github.com/Aisenkora/javaqa_team_diplom/assets/164934661/dc8a4cf2-9a95-442c-88ca-35f475eef02c)

# Окружение

Операционная система: Windows 10
IDE: IntelliJ IDEA Community Edition 2024.1.2
Java: OpenJDK 11

@KseniiaVv

**Comment by KseniiaVv** [comment]
fix #1, #2, #3, #4, #5
